### ISSUE TITLE
how spiffs mount filesystem？

### ISSUE THREAD

**Issue by oska874** [pellepl/spiffs#33]
I read the code of SPIFFS_mount(), but I didnot find you get information from flash. So how did spiffs mount filesystem ,construct file information.
What's more, how did spiff do with suddenly power loss ?

**Comment by pellepl** [comment]
Well, at mount, if SPIFFS_USE_MAGIC is not enabled, not much happens. Spiffs is designed for low memory, so everything is fetched lazily. If cache is enabled, spiffs will try to cache things, but only when requested.

If SPIFFS_USE_MAGIC is enabled, mounting will look through all blocks for the magic. Else as above.

As for sudden power loss, there are some attempts to self healing. Otherwise, a SPIFFS_check will find errors and try to mend them. However, it is up to the user to sense powerlosses.
